### ISSUE TITLE
Robotic Arm (OWI-535) need usb Interface ?

### ISSUE THREAD

**Issue by boystray** [zfw1226/craves_control#1]
does it need OWI USB Interface for Robotic Arm Edge to drive robotic arm?

**Comment by zfw1226** [comment]
Yes, the USB interface is needed to send the control command to the ARM.
Currently, we use the official [OWI USB Interface](https://www.amazon.com/OWI-USB-Interface-Robotic-Arm/dp/B0028MBWS2) for convenient. But it is a little expensive(~$40). In fact, the cost for the USB interface could be decreased. 
For example, if you have an Arduino or other MCU, you can DIY a USB interface as [this tutorial](https://www.instructables.com/id/Intro-and-what-youll-need/).

**Comment by boystray** [comment]
ok,i try to make it work
