### ISSUE TITLE
Ask for Instructions on Importing the Arm in the Unreal Simulator

### ISSUE THREAD

**Issue by YantianZha** [zfw1226/craves_control#11]
Hello,

I would like to use the same RL framework as in this repo to control a different arm in Unreal Engine. Could you explain how did you create the uproject file with this robot in Unreal Engine? I already know to to convert a uproject to a binary file.

After reading the paper, I guess you directly imported a [whole robot model](https://3dwarehouse.sketchup.com/model/u21290a3e-f8ef-46da-985c-9aa56b0dee53/Maplin-OWI-ROBOTIC-ARM) into UE without using URDF etc. Is this correct? Maybe you could explain the procedure of importing a robot into UE Editor into detail.

Also after reading the interface code in gym-unrealcv that communicates between this arm and UE-binary, I noted that there are some unrealcv commands that looks like to be unique. Did you create come custom unrealcv commands? If so, can you provide an example?

Also it would be great if you can provide the uproject file of this robot. This way I could know how a robot in UE is connected to unrealcv commands. For example, in US each joint has an ID, and unrealcv needs to know the mapping from an ID to that robot joint in UE. Right now I have no idea how can I do this.

Thank you!

**Comment by qiuwch** [comment]
Hi, Yantian:

Thanks for your interest in our project.

Yes, we imported the mesh directly. We edit the mesh in Maya to bind skeleton to make it animatable. 

For URDF, I don't know an automatic tool to import it. But you can import individual static meshes into the UE, then combine them in a hierarchy. I have friends doing URDF import, maybe they know more about this.

For custom unrealcv commands, yes, we implement custom commands. This is no good documentation for this yet, but I can send you source code and you can follow that. If you are interested, please send me an email and I can send you the project code.

**Comment by YantianZha** [comment]
Hi Weichao,

Thank you so much! My email: ytzha@outlook.com

I have explored different ways (plugins) to use a URDF to import robot into UE, but did not find one that can work. One of them has been deprecated and the UE version that supports unrealcv does not support that plugin. Some other plugins require a deep integration with ROS, which does not match the logic behind your framework.

Best
Yantian

**Comment by YantianZha** [comment]
Hi Weichao,

Thank you so much! I have emailed you.

Best
Yantian
