### ISSUE TITLE
Is GPU necessary？

### ISSUE THREAD

**Issue by LeonardNiu** [zfw1226/craves_control#2]
Hey, I wonder if GPU is necessary. I just want to test, not for training.

**Comment by zfw1226** [comment]
Hi, GPU is needed in two cases: 
   1. rendering the virtual environment;
   2. running the pose estimation module in real-time.
the DDPG network can run without GPU.

**Comment by xiaotaonan** [comment]
Hi,Can I run on MAC?

**Comment by zfw1226** [comment]
Sorry, you can not run on MAC. 
Because the released virtual environment is built on Linux.
