### ISSUE TITLE
exec nohup c:\users\xxx\downloads\xxx\armedge\gym-unrealcv\gym_unrealcv\envs/UnrealEnv\unrealcv_binary/LinuxNoEditor/ArmUE4/Binaries/Linux/ArmUE4 OWI_RL 'exec' 不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by cslayers** [zfw1226/craves_control#8]
After I ran this command
`python main.py --gpu-ids 0 --rescale --test --env UnrealArm-ContinuousPose-v1 --model-dir models/best.pt`

**Comment by cslayers** [comment]
seems it can not work on Windows

**Comment by zfw1226** [comment]
Yeah, the released Virtual Environments could only run on Linux.
