### ISSUE TITLE
about the pose estimation

### ISSUE THREAD

**Issue by FengHaobo** [zfw1226/craves_control#9]
Can the pose estimation code be use to estimate two robot arms in one picture?Is it very difficult to estimate the pose of two robot arms in one picture？

**Comment by qiuwch** [comment]
If these two arms are not heavily occluded, it should be easy. Just give the bounding box for each arm, then it should work. If heavily occlude each other, some special techniques such as part affinity field might be needed.

**Comment by FengHaobo** [comment]
Thank you for your suggestions, I will have a try.
